apiVersion: v1
kind: Service
metadata:
  name: mendix-service
  labels:
    app: mendix
spec:
  selector:
    app: mendix
  ports:
    - protocol: TCP
      port: 80 # 외부에서 접근할 포트
      targetPort: 8080 # 컨테이너의 Mendix 애플리케이션 포트
  type: LoadBalancer # 외부에서 접근 가능하도록 LoadBalancer 타입 사용
